version: '3.8'

services:
  client:
    build:
      context: ./SOLMoi_Frontend 
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - frontend-network

networks:
  frontend-network:
